# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopoChronia
                                 A QGIS plugin
 This plugin processes plate tectonic model input data into maps of the Earth past topography and geography.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-01
        copyright            : (C) 2024 by Florian Franziskakis
        email                : florian.franziskakis@unige.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopoChronia class from file TopoChronia.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .topo_chronia import TopoChronia
    return TopoChronia(iface)
